### ISSUE TITLE
Address reviewers' comments

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/FedKit_demo_paper#12]

**Comment by SichangHe** [comment]
It seems that a common critic is that we did not evaluate the performance, or, we did not benchmark the system.

https://github.com/FedCampus/FedKit_demo_paper/blob/475b1a8dd9c4de3bbd28423a4cdb1d55cd24769d/IEEEdraft0/acceptance_email.md?plain=1#L213-L214

https://github.com/FedCampus/FedKit_demo_paper/blob/475b1a8dd9c4de3bbd28423a4cdb1d55cd24769d/IEEEdraft0/acceptance_email.md?plain=1#L266-L268

https://github.com/FedCampus/FedKit_demo_paper/blob/475b1a8dd9c4de3bbd28423a4cdb1d55cd24769d/IEEEdraft0/acceptance_email.md?plain=1#L304-L306

https://github.com/FedCampus/FedKit_demo_paper/blob/475b1a8dd9c4de3bbd28423a4cdb1d55cd24769d/IEEEdraft0/acceptance_email.md?plain=1#L313-L318

https://github.com/FedCampus/FedKit_demo_paper/blob/475b1a8dd9c4de3bbd28423a4cdb1d55cd24769d/IEEEdraft0/acceptance_email.md?plain=1#L372-L374

I don't know how to address these… We did say that "FedKit will provide real-world statistics", not that it has.

@SHAO-Jiaqi757, any idea how to address these?

**Comment by SichangHe** [comment]
> they selected 4 algorithms and 3 datasets for evaluation.

@SHAO-Jiaqi757, I think space is a big problem for showing something like this, and setting up different datasets is a non-starter for us. It is more like how we can show what happens with the different phones.

**Comment by SHAO-Jiaqi757** [comment]
> > they selected 4 algorithms and 3 datasets for evaluation.
> 
> @SHAO-Jiaqi757, I think space is a big problem for showing something like this, and setting up different datasets is a non-starter for us. It is more like how we can show what happens with the different phones.

Firstly, I think the reviewers' feedbacks suggest we provide a more robust demonstration, i.e. using different datasets and algorithms. That is required to be a part of the "framework" or "system" paper. If it allows an appendix, we'd better add those benchmarks. Otherwise, we'd explain why using one experiment could show the robustness; 
Secondly, considering different phones from manufacturers serves as a demonstration for FL under heterogeneous computation resources (Table II).
